name: mutli-jobs
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Build
              run: echo "project is building stage"

            - name: write the file
              run: echo "hi hello welcome to git hub actions" >> naveen.txt

            - name: upload the file
              uses: actions/upload-artifacts@v3
              with:
                name: naveen.txt-file
                path: naveen.txt

            - name: sleep
              run: sleep 20
    
    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Test
              run: echo "project is test phase"
              
            - name: download the file
              uses: actions/download-artifacts@v3
              with:
                name: naveen.txt

            - name: read the download file
              run: cat naveen.txt

            - name: sleep
              run: sleep 10

    deploy:
        runs-on: ubuntu-latest
        needs: [build,test]

        steps:
            - name: deploy
              run: echo "deploying the cod ein env"
